name: Deploy to InfinityFree (FTP)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftpupload.net
          username: if0_41455486
          password: Arockia02
          server-dir: /htdocs/
          local-dir: ./
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            README.md
            *.sql
